---
with-expecter: true
filename: "mock_{{.InterfaceName | snakecase}}.go"
packages:
  github.com/ncotds/nco-lib/dbconnector:
    config:
      dir: "{{.InterfaceDir}}/mocks"
    interfaces:
      ExecutorCloser:
      DBConnector: